### ISSUE TITLE
vue map libre

### ISSUE THREAD

**Issue by vdcrea** [maplibre/awesome-maplibre#25]
Hello,
First of all, thanks to the team for maplibre js (and thanks to mapbox too btw).
I worked on a lib for vue 3, if you are interested I can update the cd to deploy to npm
Demo: https://atlastories.app.gitlab.io/vue-maplibre
Repo: https://gitlab.com/atlastories.app/vue-maplibre

**Comment by vdcrea** [comment]
Yes true there is already a vue 3 plugin, it lacks of v-model (two way binding props) and I am not really sure the props are truly reactive, meaning that if you change the value of a layout property the method setLayoutProperty won't trigger. That's why I coded another one. Just another happy mess in js.
I wanted to simplify the props so i prefered to cut down the 'layout' and 'paint' properties so the component observe change on each prop.

instead of <component :layout="{ component-color: 'orange' }" /> (from the existing lib)

here it s <component color="orange" /> that's the opinionated part.

**Comment by HarelM** [comment]
Does the library you have has a npm package?
Why not fork an existing one (for example vuemabox) and adjust it to maplibre?
I'm maintaining ngx-maplibre-gl but I did not create it from scratch as it has a lot of quirks when it comes to 2 way binding with layers and sources when removing and adding those.
In any case, as I said, I'm good with adding it here.

**Comment by vdcrea** [comment]
for now it s not published on npm, only in the gitlab registry https://gitlab.com/atlastories.app/vue-maplibre/-/packages/11321276
I contacted the author of [vue-maplibre-gl](https://www.npmjs.com/package/vue-maplibre-gl).

Good question, about forking vuemapbox, I wanted to learn the maplibre/mapbox api rather than finding the diff/adapting. Also I tend to prefer the `<script setup>` [syntax for vue3](https://vuejs.org/api/sfc-script-setup.html) components and it s probably a shitload of work to remove all the `this.` from vue-mapbox

**Comment by birkskyum** [comment]
@vdcrea if `@atlastories/vue-maplibre` was public on npm, then it could be added. Seems to be private.
